Update 4-reload_gunicorn_no_downtime

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,7 +1,16 @@
 #!/usr/bin/env bash
 # The script restarts gunicorn app
 
-# Get the PID of the Gunicorn process
-PID=$(pgrep gunicorn | head -n 1)
-# Send a HUP signal to the process to gracefully reload the workers
-kill -HUP "$PID"
+# Find the Gunicorn master process ID
+gunicorn_master_pid=$(ps aux | grep gunicorn | grep -v grep | awk '{if($3 == 0.0) print $2}')
+
+# Check if the Gunicorn master process ID was found
+if [ -z "$gunicorn_master_pid" ]; then
+    echo "Gunicorn master process not found."
+    exit 1
+fi
+
+# Send the HUP signal to the Gunicorn master process to gracefully reload
+kill -HUP $gunicorn_master_pid
+
+echo "Gunicorn has been gracefully reloaded."
